#include <genesis.h>
#include "data_types.h"
#include "data_load.h"

// ---- Categories ----
const char * const CATEGORY_NAMES[] = {
  "geography",
  "history",
  "music",
  "science",
  "sports",
  "videogames",
};
const u16 CATEGORY_COUNT = 6;

// ---- Questions ----
static const Question QUESTIONS_DATA[] = {
  {
    .id = 0,
    .category_id = 4,
    .question = "Which country won the 2018 FIFA World Cup?",
    .answerA = "Germany",
    .answerB = "France",
    .answerC = "Brazil",
    .correct = 1,
  },
  {
    .id = 1,
    .category_id = 4,
    .question = "In basketball how many points is a free throw worth?",
    .answerA = "1",
    .answerB = "2",
    .answerC = "3",
    .correct = 0,
  },
  {
    .id = 2,
    .category_id = 4,
    .question = "Who has won the most Olympic gold medals?",
    .answerA = "Usain Bolt",
    .answerB = "Michael Phelps",
    .answerC = "Carl Lewis",
    .correct = 1,
  },
  {
    .id = 3,
    .category_id = 4,
    .question = "Which sport uses the term 'love' for zero?",
    .answerA = "Badminton",
    .answerB = "Tennis",
    .answerC = "Cricket",
    .correct = 1,
  },
  {
    .id = 4,
    .category_id = 4,
    .question = "Where were the 2016 Summer Olympics held?",
    .answerA = "Tokyo",
    .answerB = "Rio de Janeiro",
    .answerC = "London",
    .correct = 1,
  },
  {
    .id = 5,
    .category_id = 4,
    .question = "Which country hosts the Tour de France?",
    .answerA = "Spain",
    .answerB = "France",
    .answerC = "Italy",
    .correct = 1,
  },
  {
    .id = 6,
    .category_id = 4,
    .question = "How long is a marathon?",
    .answerA = "26.2 miles",
    .answerB = "24.5 miles",
    .answerC = "28 miles",
    .correct = 0,
  },
  {
    .id = 7,
    .category_id = 4,
    .question = "Which NFL team has won the most Super Bowls?",
    .answerA = "Dallas Cowboys",
    .answerB = "New England Patriots",
    .answerC = "Pittsburgh Steelers",
    .correct = 2,
  },
  {
    .id = 8,
    .category_id = 4,
    .question = "Who is known as \"The King\" in football (soccer)?",
    .answerA = "Maradona",
    .answerB = "Pelé",
    .answerC = "Messi",
    .correct = 1,
  },
  {
    .id = 9,
    .category_id = 4,
    .question = "What is the term for one stroke under par in golf?",
    .answerA = "Eagle",
    .answerB = "Birdie",
    .answerC = "Bogey",
    .correct = 1,
  },
  {
    .id = 10,
    .category_id = 2,
    .question = "Who is known as the \"King of Pop\"?",
    .answerA = "Elvis Presley",
    .answerB = "Michael Jackson",
    .answerC = "Prince",
    .correct = 1,
  },
  {
    .id = 11,
    .category_id = 2,
    .question = "Which band released the album \"Abbey Road\"?",
    .answerA = "The Rolling Stones",
    .answerB = "The Beatles",
    .answerC = "Queen",
    .correct = 1,
  },
  {
    .id = 12,
    .category_id = 2,
    .question = "What instrument does a pianist play?",
    .answerA = "Guitar",
    .answerB = "Piano",
    .answerC = "Drums",
    .correct = 1,
  },
  {
    .id = 13,
    .category_id = 2,
    .question = "Who sang \"Someone Like You\"?",
    .answerA = "Adele",
    .answerB = "Taylor Swift",
    .answerC = "Beyoncé",
    .correct = 0,
  },
  {
    .id = 14,
    .category_id = 2,
    .question = "Which music genre is associated with Bob Marley?",
    .answerA = "Reggae",
    .answerB = "Rock",
    .answerC = "Jazz",
    .correct = 0,
  },
  {
    .id = 15,
    .category_id = 2,
    .question = "What is the highest male singing voice?",
    .answerA = "Baritone",
    .answerB = "Tenor",
    .answerC = "Bass",
    .correct = 1,
  },
  {
    .id = 16,
    .category_id = 2,
    .question = "Who was the lead singer of Queen?",
    .answerA = "Freddie Mercury",
    .answerB = "David Bowie",
    .answerC = "Robert Plant",
    .correct = 0,
  },
  {
    .id = 17,
    .category_id = 2,
    .question = "Which country did K-pop originate from?",
    .answerA = "Japan",
    .answerB = "China",
    .answerC = "South Korea",
    .correct = 2,
  },
  {
    .id = 18,
    .category_id = 2,
    .question = "Which classical composer became deaf?",
    .answerA = "Beethoven",
    .answerB = "Mozart",
    .answerC = "Chopin",
    .correct = 0,
  },
  {
    .id = 19,
    .category_id = 2,
    .question = "Who sang the hit song \"Blinding Lights\"?",
    .answerA = "The Weeknd",
    .answerB = "Drake",
    .answerC = "Post Malone",
    .correct = 0,
  },
  {
    .id = 20,
    .category_id = 0,
    .question = "What is the capital of France?",
    .answerA = "Rome",
    .answerB = "Paris",
    .answerC = "Berlin",
    .correct = 1,
  },
  {
    .id = 21,
    .category_id = 0,
    .question = "Which continent is the Sahara Desert located in?",
    .answerA = "Asia",
    .answerB = "Australia",
    .answerC = "Africa",
    .correct = 2,
  },
  {
    .id = 22,
    .category_id = 0,
    .question = "Mount Everest lies on the border of Nepal and which country?",
    .answerA = "India",
    .answerB = "China",
    .answerC = "Bhutan",
    .correct = 1,
  },
  {
    .id = 23,
    .category_id = 0,
    .question = "What is the largest ocean on Earth?",
    .answerA = "Atlantic",
    .answerB = "Pacific",
    .answerC = "Indian",
    .correct = 1,
  },
  {
    .id = 24,
    .category_id = 0,
    .question = "Which country has the most people?",
    .answerA = "India",
    .answerB = "USA",
    .answerC = "China",
    .correct = 0,
  },
  {
    .id = 25,
    .category_id = 0,
    .question = "What is the longest river in the world?",
    .answerA = "Amazon",
    .answerB = "Nile",
    .answerC = "Mississippi",
    .correct = 1,
  },
  {
    .id = 26,
    .category_id = 0,
    .question = "Which U.S. state is known as \"The Sunshine State\"?",
    .answerA = "California",
    .answerB = "Florida",
    .answerC = "Texas",
    .correct = 1,
  },
  {
    .id = 27,
    .category_id = 0,
    .question = "What is the smallest country in the world?",
    .answerA = "Monaco",
    .answerB = "Vatican City",
    .answerC = "San Marino",
    .correct = 1,
  },
  {
    .id = 28,
    .category_id = 0,
    .question = "Which desert covers much of northern Africa?",
    .answerA = "Gobi",
    .answerB = "Sahara",
    .answerC = "Kalahari",
    .correct = 1,
  },
  {
    .id = 29,
    .category_id = 0,
    .question = "Which city is known as the \"Big Apple\"?",
    .answerA = "Los Angeles",
    .answerB = "Chicago",
    .answerC = "New York City",
    .correct = 2,
  },
  {
    .id = 30,
    .category_id = 1,
    .question = "When did World War II end?",
    .answerA = "1943",
    .answerB = "1945",
    .answerC = "1947",
    .correct = 1,
  },
  {
    .id = 31,
    .category_id = 1,
    .question = "Who was the first President of the United States?",
    .answerA = "George Washington",
    .answerB = "Thomas Jefferson",
    .answerC = "Abraham Lincoln",
    .correct = 0,
  },
  {
    .id = 32,
    .category_id = 1,
    .question = "In which year did the Titanic sink?",
    .answerA = "1910",
    .answerB = "1912",
    .answerC = "1914",
    .correct = 1,
  },
  {
    .id = 33,
    .category_id = 1,
    .question = "Who discovered America in 1492?",
    .answerA = "Christopher Columbus",
    .answerB = "Ferdinand Magellan",
    .answerC = "Marco Polo",
    .correct = 0,
  },
  {
    .id = 34,
    .category_id = 1,
    .question = "What wall fell in 1989 symbolizing the end of the Cold War?",
    .answerA = "Berlin Wall",
    .answerB = "Great Wall of China",
    .answerC = "Hadrian’s Wall",
    .correct = 0,
  },
  {
    .id = 35,
    .category_id = 1,
    .question = "Who was the British Prime Minister during most of World War II?",
    .answerA = "Winston Churchill",
    .answerB = "Neville Chamberlain",
    .answerC = "Margaret Thatcher",
    .correct = 0,
  },
  {
    .id = 36,
    .category_id = 1,
    .question = "Which empire built the Colosseum?",
    .answerA = "Greek",
    .answerB = "Roman",
    .answerC = "Byzantine",
    .correct = 1,
  },
  {
    .id = 37,
    .category_id = 1,
    .question = "What was the name of the ship that brought the Pilgrims to America?",
    .answerA = "Santa Maria",
    .answerB = "Mayflower",
    .answerC = "Endeavour",
    .correct = 1,
  },
  {
    .id = 38,
    .category_id = 1,
    .question = "Who was known as the Maid of Orléans?",
    .answerA = "Catherine the Great",
    .answerB = "Joan of Arc",
    .answerC = "Marie Antoinette",
    .correct = 1,
  },
  {
    .id = 39,
    .category_id = 1,
    .question = "In which year did humans first land on the moon?",
    .answerA = "1965",
    .answerB = "1969",
    .answerC = "1972",
    .correct = 1,
  },
  {
    .id = 40,
    .category_id = 3,
    .question = "What planet is known as the Red Planet?",
    .answerA = "Venus",
    .answerB = "Mars",
    .answerC = "Jupiter",
    .correct = 1,
  },
  {
    .id = 41,
    .category_id = 3,
    .question = "What is the chemical symbol for water?",
    .answerA = "H2O",
    .answerB = "O2",
    .answerC = "CO2",
    .correct = 0,
  },
  {
    .id = 42,
    .category_id = 3,
    .question = "How many bones are in the adult human body?",
    .answerA = "206",
    .answerB = "210",
    .answerC = "215",
    .correct = 0,
  },
  {
    .id = 43,
    .category_id = 3,
    .question = "What gas do plants absorb during photosynthesis?",
    .answerA = "Oxygen",
    .answerB = "Carbon Dioxide",
    .answerC = "Nitrogen",
    .correct = 1,
  },
  {
    .id = 44,
    .category_id = 3,
    .question = "What is the speed of light?",
    .answerA = "300",
    .answerB = "000 km/s",
    .answerC = "150",
    .correct = 0,
  },
  {
    .id = 45,
    .category_id = 3,
    .question = "Who developed the theory of relativity?",
    .answerA = "Isaac Newton",
    .answerB = "Albert Einstein",
    .answerC = "Galileo Galilei",
    .correct = 1,
  },
  {
    .id = 46,
    .category_id = 3,
    .question = "What part of the atom has a positive charge?",
    .answerA = "Electron",
    .answerB = "Proton",
    .answerC = "Neutron",
    .correct = 1,
  },
  {
    .id = 47,
    .category_id = 3,
    .question = "Which planet is closest to the Sun?",
    .answerA = "Venus",
    .answerB = "Mercury",
    .answerC = "Earth",
    .correct = 1,
  },
  {
    .id = 48,
    .category_id = 3,
    .question = "What is the process of water turning into vapor called?",
    .answerA = "Condensation",
    .answerB = "Evaporation",
    .answerC = "Precipitation",
    .correct = 1,
  },
  {
    .id = 49,
    .category_id = 3,
    .question = "What is the hardest natural substance on Earth?",
    .answerA = "Gold",
    .answerB = "Iron",
    .answerC = "Diamond",
    .correct = 2,
  },
  {
    .id = 50,
    .category_id = 5,
    .question = "What is the best-selling video game of all time?",
    .answerA = "Minecraft",
    .answerB = "Tetris",
    .answerC = "GTA V",
    .correct = 0,
  },
  {
    .id = 51,
    .category_id = 5,
    .question = "Which company created the PlayStation console?",
    .answerA = "Sega",
    .answerB = "Nintendo",
    .answerC = "Sony",
    .correct = 2,
  },
  {
    .id = 52,
    .category_id = 5,
    .question = "What is the name of Mario’s brother?",
    .answerA = "Luigi",
    .answerB = "Yoshi",
    .answerC = "Wario",
    .correct = 0,
  },
  {
    .id = 53,
    .category_id = 5,
    .question = "Which game features the character Master Chief?",
    .answerA = "Halo",
    .answerB = "Call of Duty",
    .answerC = "Destiny",
    .correct = 0,
  },
  {
    .id = 54,
    .category_id = 5,
    .question = "In which game do players compete in a battle royale on an island?",
    .answerA = "Overwatch",
    .answerB = "Fortnite",
    .answerC = "Apex Legends",
    .correct = 1,
  },
  {
    .id = 55,
    .category_id = 5,
    .question = "What Pokémon is number 25 in the Pokédex?",
    .answerA = "Bulbasaur",
    .answerB = "Pikachu",
    .answerC = "Charmander",
    .correct = 1,
  },
  {
    .id = 56,
    .category_id = 5,
    .question = "What is the main currency in The Legend of Zelda?",
    .answerA = "Gold",
    .answerB = "Rupees",
    .answerC = "Coins",
    .correct = 1,
  },
  {
    .id = 57,
    .category_id = 5,
    .question = "Which game series features locations like Vice City and Los Santos?",
    .answerA = "GTA",
    .answerB = "Red Dead Redemption",
    .answerC = "Saints Row",
    .correct = 0,
  },
  {
    .id = 58,
    .category_id = 5,
    .question = "Who is the creator of the game Minecraft?",
    .answerA = "Gabe Newell",
    .answerB = "Notch",
    .answerC = "Hideo Kojima",
    .correct = 1,
  },
  {
    .id = 59,
    .category_id = 5,
    .question = "Which company developed the game “Overwatch”?",
    .answerA = "Valve",
    .answerB = "Blizzard",
    .answerC = "Ubisoft",
    .correct = 1,
  },
};
const Question * const QUESTIONS = QUESTIONS_DATA;
const u16 QUESTIONS_COUNT = 60;

// ---- Scenes ----
static const Scene SCENES_DATA[] = {
  {
    .id = 0,
    .type = SCENE_TYPE_NORMAL,
    .text = "You wake up in a hospital.\n Not remembering anything,\n you get up from the bed.",
    .nextScene = 1,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 0, .music = 0,
  },
  {
    .id = 1,
    .type = SCENE_TYPE_QUIZ_TRIGGER,
    .text = "You put on a near by gown but\nSuddenly your chest hurts...",
    .nextScene = 2,
    .triggerQuiz = 0,
    .questionId = -1,
    .bg = 1, .music = 1,
  },
  {
    .id = 2,
    .type = SCENE_TYPE_NORMAL,
    .text = "But it passes. You walk outside.\n You see a stranger\n and get their attention.",
    .nextScene = 3,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 2, .music = 2,
  },
  {
    .id = 3,
    .type = SCENE_TYPE_QUIZ_TRIGGER,
    .text = "The man turns around.\n He starts walking at you bearing a knife!",
    .nextScene = 4,
    .triggerQuiz = 1,
    .questionId = -1,
    .bg = 2, .music = 2,
  },
  {
    .id = 4,
    .type = SCENE_TYPE_GOOD_ENDING,
    .text = "Oh, he just wanted to ask if you wanted a knife.\n You got \"the knife\".",
    .nextScene = -1,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 2, .music = 2,
  },
};
const Scene * const SCENES = SCENES_DATA;
const u16 SCENES_COUNT = 5;

// ---- Quizzes ----
static const u16 _QUIZ_CATS_0[] = { 1, 0, 3, 5, 2 };
static const u16 _QUIZ_CATS_1[] = { 1, 0, 3, 5, 2 };
static const Quiz QUIZZES_DATA[] = {
  {
    .id = 0,
    .name = "General Knowledge",
    .wrongLimit = 2,
    .questionCount = 3,
    .categories = _QUIZ_CATS_0,
    .categoryCount = (u16)(sizeof(_QUIZ_CATS_0)/sizeof(_QUIZ_CATS_0[0])),
  },
  {
    .id = 1,
    .name = "General Knowledge",
    .wrongLimit = 2,
    .questionCount = 5,
    .categories = _QUIZ_CATS_1,
    .categoryCount = (u16)(sizeof(_QUIZ_CATS_1)/sizeof(_QUIZ_CATS_1[0])),
  },
};
const Quiz * const QUIZZES = QUIZZES_DATA;
const u16 QUIZZES_COUNT = 2;

// ---- Category Question Indexes ----
static const u16 _CAT_QIDX_0[] = { 20, 21, 22, 23, 24, 25, 26, 27, 28, 29 };
static const u16 _CAT_QIDX_1[] = { 30, 31, 32, 33, 34, 35, 36, 37, 38, 39 };
static const u16 _CAT_QIDX_2[] = { 10, 11, 12, 13, 14, 15, 16, 17, 18, 19 };
static const u16 _CAT_QIDX_3[] = { 40, 41, 42, 43, 44, 45, 46, 47, 48, 49 };
static const u16 _CAT_QIDX_4[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
static const u16 _CAT_QIDX_5[] = { 50, 51, 52, 53, 54, 55, 56, 57, 58, 59 };
const u16 * const CATEGORY_QUESTION_INDEXES[] = {
  _CAT_QIDX_0,
  _CAT_QIDX_1,
  _CAT_QIDX_2,
  _CAT_QIDX_3,
  _CAT_QIDX_4,
  _CAT_QIDX_5,
};
const u16 CATEGORY_QUESTION_COUNTS[] = {
  10,
  10,
  10,
  10,
  10,
  10,
};
