#include <genesis.h>
#include "data_types.h"
#include "data_load.h"

// ---- Categories ----
const char * const CATEGORY_NAMES[] = {
  "geography",
  "history",
  "knowledge1",
  "knowledge2",
  "knowledge3",
  "knowledge4",
  "logic1",
  "logic2",
  "logic3",
  "logic4",
  "logic5",
  "music",
  "science",
  "sports",
  "videogames",
};
const u16 CATEGORY_COUNT = 15;

// ---- Questions ----
static const Question QUESTIONS_DATA[] = {
  {
    .id = 0,
    .category_id = 13,
    .question = "Which country won the 2018 FIFA World Cup?",
    .answerA = "Germany",
    .answerB = "France",
    .answerC = "Brazil",
    .correct = 1,
  },
  {
    .id = 1,
    .category_id = 13,
    .question = "In basketball how many points is a free throw worth?",
    .answerA = "1",
    .answerB = "2",
    .answerC = "3",
    .correct = 0,
  },
  {
    .id = 2,
    .category_id = 13,
    .question = "Who has won the most Olympic gold medals?",
    .answerA = "Usain Bolt",
    .answerB = "Michael Phelps",
    .answerC = "Carl Lewis",
    .correct = 1,
  },
  {
    .id = 3,
    .category_id = 13,
    .question = "Which sport uses the term 'love' for zero?",
    .answerA = "Badminton",
    .answerB = "Tennis",
    .answerC = "Cricket",
    .correct = 1,
  },
  {
    .id = 4,
    .category_id = 13,
    .question = "Where were the 2016 Summer Olympics held?",
    .answerA = "Tokyo",
    .answerB = "Rio de Janeiro",
    .answerC = "London",
    .correct = 1,
  },
  {
    .id = 5,
    .category_id = 13,
    .question = "Which country hosts the Tour de France?",
    .answerA = "Spain",
    .answerB = "France",
    .answerC = "Italy",
    .correct = 1,
  },
  {
    .id = 6,
    .category_id = 13,
    .question = "How long is a marathon?",
    .answerA = "26.2 miles",
    .answerB = "24.5 miles",
    .answerC = "28 miles",
    .correct = 0,
  },
  {
    .id = 7,
    .category_id = 13,
    .question = "Which NFL team has won the most Super Bowls?",
    .answerA = "Dallas Cowboys",
    .answerB = "New England Patriots",
    .answerC = "Pittsburgh Steelers",
    .correct = 2,
  },
  {
    .id = 8,
    .category_id = 13,
    .question = "Who is known as \"The King\" in football (soccer)?",
    .answerA = "Maradona",
    .answerB = "Pelé",
    .answerC = "Messi",
    .correct = 1,
  },
  {
    .id = 9,
    .category_id = 13,
    .question = "What is the term for one stroke under par in golf?",
    .answerA = "Eagle",
    .answerB = "Birdie",
    .answerC = "Bogey",
    .correct = 1,
  },
  {
    .id = 10,
    .category_id = 11,
    .question = "Who is known as the \"King of Pop\"?",
    .answerA = "Elvis Presley",
    .answerB = "Michael Jackson",
    .answerC = "Prince",
    .correct = 1,
  },
  {
    .id = 11,
    .category_id = 11,
    .question = "Which band released the album \"Abbey Road\"?",
    .answerA = "The Rolling Stones",
    .answerB = "The Beatles",
    .answerC = "Queen",
    .correct = 1,
  },
  {
    .id = 12,
    .category_id = 11,
    .question = "What instrument does a pianist play?",
    .answerA = "Guitar",
    .answerB = "Piano",
    .answerC = "Drums",
    .correct = 1,
  },
  {
    .id = 13,
    .category_id = 11,
    .question = "Who sang \"Someone Like You\"?",
    .answerA = "Adele",
    .answerB = "Taylor Swift",
    .answerC = "Beyoncé",
    .correct = 0,
  },
  {
    .id = 14,
    .category_id = 11,
    .question = "Which music genre is associated with Bob Marley?",
    .answerA = "Reggae",
    .answerB = "Rock",
    .answerC = "Jazz",
    .correct = 0,
  },
  {
    .id = 15,
    .category_id = 11,
    .question = "What is the highest male singing voice?",
    .answerA = "Baritone",
    .answerB = "Tenor",
    .answerC = "Bass",
    .correct = 1,
  },
  {
    .id = 16,
    .category_id = 11,
    .question = "Who was the lead singer of Queen?",
    .answerA = "Freddie Mercury",
    .answerB = "David Bowie",
    .answerC = "Robert Plant",
    .correct = 0,
  },
  {
    .id = 17,
    .category_id = 11,
    .question = "Which country did K-pop originate from?",
    .answerA = "Japan",
    .answerB = "China",
    .answerC = "South Korea",
    .correct = 2,
  },
  {
    .id = 18,
    .category_id = 11,
    .question = "Which classical composer became deaf?",
    .answerA = "Beethoven",
    .answerB = "Mozart",
    .answerC = "Chopin",
    .correct = 0,
  },
  {
    .id = 19,
    .category_id = 11,
    .question = "Who sang the hit song \"Blinding Lights\"?",
    .answerA = "The Weeknd",
    .answerB = "Drake",
    .answerC = "Post Malone",
    .correct = 0,
  },
  {
    .id = 20,
    .category_id = 0,
    .question = "What is the capital of France?",
    .answerA = "Rome",
    .answerB = "Paris",
    .answerC = "Berlin",
    .correct = 1,
  },
  {
    .id = 21,
    .category_id = 0,
    .question = "Which continent is the Sahara Desert located in?",
    .answerA = "Asia",
    .answerB = "Australia",
    .answerC = "Africa",
    .correct = 2,
  },
  {
    .id = 22,
    .category_id = 0,
    .question = "Mount Everest lies on the border of Nepal and which country?",
    .answerA = "India",
    .answerB = "China",
    .answerC = "Bhutan",
    .correct = 1,
  },
  {
    .id = 23,
    .category_id = 0,
    .question = "What is the largest ocean on Earth?",
    .answerA = "Atlantic",
    .answerB = "Pacific",
    .answerC = "Indian",
    .correct = 1,
  },
  {
    .id = 24,
    .category_id = 0,
    .question = "Which country has the most people?",
    .answerA = "India",
    .answerB = "USA",
    .answerC = "China",
    .correct = 0,
  },
  {
    .id = 25,
    .category_id = 0,
    .question = "What is the longest river in the world?",
    .answerA = "Amazon",
    .answerB = "Nile",
    .answerC = "Mississippi",
    .correct = 1,
  },
  {
    .id = 26,
    .category_id = 0,
    .question = "Which U.S. state is known as \"The Sunshine State\"?",
    .answerA = "California",
    .answerB = "Florida",
    .answerC = "Texas",
    .correct = 1,
  },
  {
    .id = 27,
    .category_id = 0,
    .question = "What is the smallest country in the world?",
    .answerA = "Monaco",
    .answerB = "Vatican City",
    .answerC = "San Marino",
    .correct = 1,
  },
  {
    .id = 28,
    .category_id = 0,
    .question = "Which desert covers much of northern Africa?",
    .answerA = "Gobi",
    .answerB = "Sahara",
    .answerC = "Kalahari",
    .correct = 1,
  },
  {
    .id = 29,
    .category_id = 0,
    .question = "Which city is known as the \"Big Apple\"?",
    .answerA = "Los Angeles",
    .answerB = "Chicago",
    .answerC = "New York City",
    .correct = 2,
  },
  {
    .id = 30,
    .category_id = 1,
    .question = "When did World War II end?",
    .answerA = "1943",
    .answerB = "1945",
    .answerC = "1947",
    .correct = 1,
  },
  {
    .id = 31,
    .category_id = 1,
    .question = "Who was the first President of the United States?",
    .answerA = "George Washington",
    .answerB = "Thomas Jefferson",
    .answerC = "Abraham Lincoln",
    .correct = 0,
  },
  {
    .id = 32,
    .category_id = 1,
    .question = "In which year did the Titanic sink?",
    .answerA = "1910",
    .answerB = "1912",
    .answerC = "1914",
    .correct = 1,
  },
  {
    .id = 33,
    .category_id = 1,
    .question = "Who discovered America in 1492?",
    .answerA = "Christopher Columbus",
    .answerB = "Ferdinand Magellan",
    .answerC = "Marco Polo",
    .correct = 0,
  },
  {
    .id = 34,
    .category_id = 1,
    .question = "What wall fell in 1989 symbolizing the end of the Cold War?",
    .answerA = "Berlin Wall",
    .answerB = "Great Wall of China",
    .answerC = "Hadrian’s Wall",
    .correct = 0,
  },
  {
    .id = 35,
    .category_id = 1,
    .question = "Who was the British Prime Minister during most of World War II?",
    .answerA = "Winston Churchill",
    .answerB = "Neville Chamberlain",
    .answerC = "Margaret Thatcher",
    .correct = 0,
  },
  {
    .id = 36,
    .category_id = 1,
    .question = "Which empire built the Colosseum?",
    .answerA = "Greek",
    .answerB = "Roman",
    .answerC = "Byzantine",
    .correct = 1,
  },
  {
    .id = 37,
    .category_id = 1,
    .question = "What was the name of the ship that brought the Pilgrims to America?",
    .answerA = "Santa Maria",
    .answerB = "Mayflower",
    .answerC = "Endeavour",
    .correct = 1,
  },
  {
    .id = 38,
    .category_id = 1,
    .question = "Who was known as the Maid of Orléans?",
    .answerA = "Catherine the Great",
    .answerB = "Joan of Arc",
    .answerC = "Marie Antoinette",
    .correct = 1,
  },
  {
    .id = 39,
    .category_id = 1,
    .question = "In which year did humans first land on the moon?",
    .answerA = "1965",
    .answerB = "1969",
    .answerC = "1972",
    .correct = 1,
  },
  {
    .id = 40,
    .category_id = 12,
    .question = "What planet is known as the Red Planet?",
    .answerA = "Venus",
    .answerB = "Mars",
    .answerC = "Jupiter",
    .correct = 1,
  },
  {
    .id = 41,
    .category_id = 12,
    .question = "What is the chemical symbol for water?",
    .answerA = "H2O",
    .answerB = "O2",
    .answerC = "CO2",
    .correct = 0,
  },
  {
    .id = 42,
    .category_id = 12,
    .question = "How many bones are in the adult human body?",
    .answerA = "206",
    .answerB = "210",
    .answerC = "215",
    .correct = 0,
  },
  {
    .id = 43,
    .category_id = 12,
    .question = "What gas do plants absorb during photosynthesis?",
    .answerA = "Oxygen",
    .answerB = "Carbon Dioxide",
    .answerC = "Nitrogen",
    .correct = 1,
  },
  {
    .id = 44,
    .category_id = 12,
    .question = "What is the speed of light?",
    .answerA = "300",
    .answerB = "000 km/s",
    .answerC = "150",
    .correct = 0,
  },
  {
    .id = 45,
    .category_id = 12,
    .question = "Who developed the theory of relativity?",
    .answerA = "Isaac Newton",
    .answerB = "Albert Einstein",
    .answerC = "Galileo Galilei",
    .correct = 1,
  },
  {
    .id = 46,
    .category_id = 12,
    .question = "What part of the atom has a positive charge?",
    .answerA = "Electron",
    .answerB = "Proton",
    .answerC = "Neutron",
    .correct = 1,
  },
  {
    .id = 47,
    .category_id = 12,
    .question = "Which planet is closest to the Sun?",
    .answerA = "Venus",
    .answerB = "Mercury",
    .answerC = "Earth",
    .correct = 1,
  },
  {
    .id = 48,
    .category_id = 12,
    .question = "What is the process of water turning into vapor called?",
    .answerA = "Condensation",
    .answerB = "Evaporation",
    .answerC = "Precipitation",
    .correct = 1,
  },
  {
    .id = 49,
    .category_id = 12,
    .question = "What is the hardest natural substance on Earth?",
    .answerA = "Gold",
    .answerB = "Iron",
    .answerC = "Diamond",
    .correct = 2,
  },
  {
    .id = 50,
    .category_id = 14,
    .question = "What is the best-selling video game of all time?",
    .answerA = "Minecraft",
    .answerB = "Tetris",
    .answerC = "GTA V",
    .correct = 0,
  },
  {
    .id = 51,
    .category_id = 14,
    .question = "Which company created the PlayStation console?",
    .answerA = "Sega",
    .answerB = "Nintendo",
    .answerC = "Sony",
    .correct = 2,
  },
  {
    .id = 52,
    .category_id = 14,
    .question = "What is the name of Mario’s brother?",
    .answerA = "Luigi",
    .answerB = "Yoshi",
    .answerC = "Wario",
    .correct = 0,
  },
  {
    .id = 53,
    .category_id = 14,
    .question = "Which game features the character Master Chief?",
    .answerA = "Halo",
    .answerB = "Call of Duty",
    .answerC = "Destiny",
    .correct = 0,
  },
  {
    .id = 54,
    .category_id = 14,
    .question = "In which game do players compete in a battle royale on an island?",
    .answerA = "Overwatch",
    .answerB = "Fortnite",
    .answerC = "Apex Legends",
    .correct = 1,
  },
  {
    .id = 55,
    .category_id = 14,
    .question = "What Pokémon is number 25 in the Pokédex?",
    .answerA = "Bulbasaur",
    .answerB = "Pikachu",
    .answerC = "Charmander",
    .correct = 1,
  },
  {
    .id = 56,
    .category_id = 14,
    .question = "What is the main currency in The Legend of Zelda?",
    .answerA = "Gold",
    .answerB = "Rupees",
    .answerC = "Coins",
    .correct = 1,
  },
  {
    .id = 57,
    .category_id = 14,
    .question = "Which game series features locations like Vice City and Los Santos?",
    .answerA = "GTA",
    .answerB = "Red Dead Redemption",
    .answerC = "Saints Row",
    .correct = 0,
  },
  {
    .id = 58,
    .category_id = 14,
    .question = "Who is the creator of the game Minecraft?",
    .answerA = "Gabe Newell",
    .answerB = "Notch",
    .answerC = "Hideo Kojima",
    .correct = 1,
  },
  {
    .id = 59,
    .category_id = 14,
    .question = "Which company developed the game “Overwatch”?",
    .answerA = "Valve",
    .answerB = "Blizzard",
    .answerC = "Ubisoft",
    .correct = 1,
  },
  {
    .id = 60,
    .category_id = 6,
    .question = "1.1.2.3.5... What comes next?",
    .answerA = "8",
    .answerB = "9",
    .answerC = "10",
    .correct = 0,
  },
  {
    .id = 61,
    .category_id = 7,
    .question = "If English is English what's Japanese?",
    .answerA = "Japanese",
    .answerB = "Nihongo",
    .answerC = "English",
    .correct = 2,
  },
  {
    .id = 62,
    .category_id = 8,
    .question = "If a book costs $1 plus half its cost what's its cost?",
    .answerA = "$1.50",
    .answerB = "$1.75",
    .answerC = "$2.00",
    .correct = 2,
  },
  {
    .id = 63,
    .category_id = 9,
    .question = "What to ask one always honest and one always lying guards?",
    .answerA = "Which way?",
    .answerB = "Other guard's choice",
    .answerC = "Who is a liar?",
    .correct = 1,
  },
  {
    .id = 64,
    .category_id = 10,
    .question = "Wolf goat and cabbage. Cross with which first?",
    .answerA = "Wolf",
    .answerB = "Goat",
    .answerC = "Cabbage",
    .correct = 1,
  },
  {
    .id = 65,
    .category_id = 2,
    .question = "What is the C Major third?",
    .answerA = "E",
    .answerB = "F",
    .answerC = "G",
    .correct = 0,
  },
  {
    .id = 66,
    .category_id = 3,
    .question = "Whose philosophy is quoted as 'I think therefore I am'?",
    .answerA = "Jean-Paul Sartre",
    .answerB = "Aristotle",
    .answerC = "Rene Descartes",
    .correct = 2,
  },
  {
    .id = 67,
    .category_id = 4,
    .question = "Which was invented first?",
    .answerA = "Sandwich",
    .answerB = "Sliced bread",
    .answerC = "Mahjong",
    .correct = 0,
  },
  {
    .id = 68,
    .category_id = 5,
    .question = "What phenomena does Schrodinger's Cat explore?",
    .answerA = "Logic puzzles",
    .answerB = "Quantum mechanics",
    .answerC = "Cognitive dissonance",
    .correct = 1,
  },
};
const Question * const QUESTIONS = QUESTIONS_DATA;
const u16 QUESTIONS_COUNT = 69;

// ---- Scenes ----
static const Scene SCENES_DATA[] = {
  {
    .id = 0,
    .type = SCENE_TYPE_NORMAL,
    .text = "Intuition is somewhat magical in a dream. \nYou don't know why, but you make these connections \nbetween what you need to do and what is correct.",
    .nextSceneA = 1,
    .nextSceneB = 1,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 0, .music = 1,
  },
  {
    .id = 1,
    .type = SCENE_TYPE_NORMAL,
    .text = "Perhaps you're still in a dream when you wake, \nwhen you find yourself in an empty room.",
    .nextSceneA = 2,
    .nextSceneB = 2,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 0, .music = 1,
  },
  {
    .id = 2,
    .type = SCENE_TYPE_NORMAL,
    .text = "You feel like you should know what to do next. \nMaybe you do know what to do next. \nMaybe you've always known. \nOr maybe you're just learning.",
    .nextSceneA = 3,
    .nextSceneB = 3,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 0, .music = 1,
  },
  {
    .id = 3,
    .type = SCENE_TYPE_QUIZ_TRIGGER,
    .text = "Maybe if you focus on what you do know, the rest will come naturally. \n\nStart small.",
    .nextSceneA = 5,
    .nextSceneB = 4,
    .triggerQuiz = -1,
    .questionId = 60,
    .bg = 0, .music = 1,
  },
  {
    .id = 4,
    .type = SCENE_TYPE_BAD_ENDING,
    .text = "You turn to the red door. \nIt seems like the only door you could enter. \nIt's only natural that you enter it.",
    .nextSceneA = -1,
    .nextSceneB = -1,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 2, .music = 0,
  },
  {
    .id = 5,
    .type = SCENE_TYPE_QUIZ_TRIGGER,
    .text = "A voice slithers from the corner of the room. \nIt chills you to the bone and freezes you in place. \nNOW YOU MUST ANSWER!",
    .nextSceneA = 13,
    .nextSceneB = 9,
    .triggerQuiz = -1,
    .questionId = 65,
    .bg = 4, .music = 2,
  },
  {
    .id = 6,
    .type = SCENE_TYPE_QUIZ_TRIGGER,
    .text = "A voice slithers from the corner of the room. \nIt chills you to the bone and freezes you in place. \nNOW YOU MUST ANSWER!",
    .nextSceneA = 14,
    .nextSceneB = 10,
    .triggerQuiz = -1,
    .questionId = 66,
    .bg = 4, .music = 2,
  },
  {
    .id = 7,
    .type = SCENE_TYPE_QUIZ_TRIGGER,
    .text = "A voice slithers from the corner of the room. \nIt chills you to the bone and freezes you in place. \nNOW YOU MUST ANSWER!",
    .nextSceneA = 15,
    .nextSceneB = 11,
    .triggerQuiz = -1,
    .questionId = 67,
    .bg = 4, .music = 2,
  },
  {
    .id = 8,
    .type = SCENE_TYPE_QUIZ_TRIGGER,
    .text = "A voice slithers from the corner of the room. \nIt chills you to the bone and freezes you in place. \nNOW YOU MUST ANSWER!",
    .nextSceneA = 16,
    .nextSceneB = 12,
    .triggerQuiz = -1,
    .questionId = 68,
    .bg = 4, .music = 2,
  },
  {
    .id = 9,
    .type = SCENE_TYPE_NORMAL,
    .text = "The demon cackles. \nYOU'RE ON YOUR OWN!",
    .nextSceneA = 17,
    .nextSceneB = 17,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 4, .music = 2,
  },
  {
    .id = 10,
    .type = SCENE_TYPE_NORMAL,
    .text = "The demon cackles. \nYOU'RE ON YOUR OWN!",
    .nextSceneA = 19,
    .nextSceneB = 19,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 4, .music = 2,
  },
  {
    .id = 11,
    .type = SCENE_TYPE_NORMAL,
    .text = "The demon cackles. \nYOU'RE ON YOUR OWN!",
    .nextSceneA = 21,
    .nextSceneB = 21,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 4, .music = 2,
  },
  {
    .id = 12,
    .type = SCENE_TYPE_NORMAL,
    .text = "The demon cackles. \nYOU'RE ON YOUR OWN!",
    .nextSceneA = 22,
    .nextSceneB = 22,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 4, .music = 2,
  },
  {
    .id = 13,
    .type = SCENE_TYPE_NORMAL,
    .text = "The demon smiles the most awful smile. \nREMEMBER, ENGLISH IS AN ENGLISH WORD! \nREMEMBER!",
    .nextSceneA = 17,
    .nextSceneB = 17,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 4, .music = 2,
  },
  {
    .id = 14,
    .type = SCENE_TYPE_NORMAL,
    .text = "The demon smiles the most awful smile. \nREMEMBER, A THING COSTS WHAT IT COSTS! \nREMEMBER!",
    .nextSceneA = 19,
    .nextSceneB = 19,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 4, .music = 2,
  },
  {
    .id = 15,
    .type = SCENE_TYPE_NORMAL,
    .text = "The demon smiles the most awful smile. \nREMEMBER, YOU DON'T WANT TO FOLLOW A LIAR! \nREMEMBER!",
    .nextSceneA = 21,
    .nextSceneB = 21,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 4, .music = 2,
  },
  {
    .id = 16,
    .type = SCENE_TYPE_NORMAL,
    .text = "The demon smiles the most awful smile. \nREMEMBER, A WOLF WILL NOT EAT CABBAGE! \nREMEMBER!",
    .nextSceneA = 22,
    .nextSceneB = 22,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 4, .music = 2,
  },
  {
    .id = 17,
    .type = SCENE_TYPE_NORMAL,
    .text = "You begin looking around the room. \nThere's a door and... another door. \nWere there always two doors here?",
    .nextSceneA = 18,
    .nextSceneB = 18,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 0, .music = 1,
  },
  {
    .id = 18,
    .type = SCENE_TYPE_QUIZ_TRIGGER,
    .text = "You're sure there have definitely always been two doors here. \n\nNow think...",
    .nextSceneA = 6,
    .nextSceneB = 4,
    .triggerQuiz = -1,
    .questionId = 61,
    .bg = 0, .music = 1,
  },
  {
    .id = 19,
    .type = SCENE_TYPE_NORMAL,
    .text = "You reach for the green door. \nIt's locked.",
    .nextSceneA = 20,
    .nextSceneB = 20,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 3, .music = 1,
  },
  {
    .id = 20,
    .type = SCENE_TYPE_QUIZ_TRIGGER,
    .text = "Surely there are keys somewhere around here, \nif you take the time to search for them. \n\nNow think...",
    .nextSceneA = 7,
    .nextSceneB = 24,
    .triggerQuiz = -1,
    .questionId = 62,
    .bg = 0, .music = 1,
  },
  {
    .id = 21,
    .type = SCENE_TYPE_QUIZ_TRIGGER,
    .text = "You go over to the bookshelf and find a book on Lockpicking. \nHmmm, perhaps you don't need a key at all... \n\nNow think...",
    .nextSceneA = 8,
    .nextSceneB = 25,
    .triggerQuiz = -1,
    .questionId = 63,
    .bg = 0, .music = 1,
  },
  {
    .id = 22,
    .type = SCENE_TYPE_NORMAL,
    .text = "As you reach to scratch your head, you find \na bobbypin holding your hair in a bun.",
    .nextSceneA = 23,
    .nextSceneB = 23,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 0, .music = 1,
  },
  {
    .id = 23,
    .type = SCENE_TYPE_QUIZ_TRIGGER,
    .text = "Apparently, you have long, beautiful hair \nthat falls down as you remove the bobbypin. \n\nNow think...",
    .nextSceneA = 26,
    .nextSceneB = 27,
    .triggerQuiz = -1,
    .questionId = 64,
    .bg = 0, .music = 1,
  },
  {
    .id = 24,
    .type = SCENE_TYPE_NORMAL,
    .text = "You go over to the bookshelf and find a book on Algebra. \nPerhaps it's a hollow book and the key is inside? \nNope, all that's inside is knowledge.",
    .nextSceneA = 4,
    .nextSceneB = 4,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 0, .music = 0,
  },
  {
    .id = 25,
    .type = SCENE_TYPE_NORMAL,
    .text = "You set down the book on Lockpicking and \na book on Logic catches your eye. \nMaybe the key is in understanding \nthe things which you know to be true.",
    .nextSceneA = 4,
    .nextSceneB = 4,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 0, .music = 0,
  },
  {
    .id = 26,
    .type = SCENE_TYPE_NORMAL,
    .text = "As you fumble with lock, your thoughts meander... \nWhat are you doing here? \nWho are you? \nHow long have you been here?",
    .nextSceneA = 4,
    .nextSceneB = 4,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 3, .music = 0,
  },
  {
    .id = 27,
    .type = SCENE_TYPE_NORMAL,
    .text = "Despite barely understanding the book on Lockpicking, \nyou effortlessly unlock the door with the bobbypin.",
    .nextSceneA = 28,
    .nextSceneB = 28,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 3, .music = 1,
  },
  {
    .id = 28,
    .type = SCENE_TYPE_NORMAL,
    .text = "Maybe you do this professionally in another life.",
    .nextSceneA = 29,
    .nextSceneB = 29,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 3, .music = 1,
  },
  {
    .id = 29,
    .type = SCENE_TYPE_NORMAL,
    .text = "Maybe you're married in another life.",
    .nextSceneA = 30,
    .nextSceneB = 30,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 3, .music = 1,
  },
  {
    .id = 30,
    .type = SCENE_TYPE_NORMAL,
    .text = "Maybe you're an artist in another life.",
    .nextSceneA = 31,
    .nextSceneB = 31,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 3, .music = 1,
  },
  {
    .id = 31,
    .type = SCENE_TYPE_NORMAL,
    .text = "Who are you really?",
    .nextSceneA = 32,
    .nextSceneB = 32,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 3, .music = 1,
  },
  {
    .id = 32,
    .type = SCENE_TYPE_NORMAL,
    .text = "You step through the door and wake up.",
    .nextSceneA = 33,
    .nextSceneB = 33,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 3, .music = 1,
  },
  {
    .id = 33,
    .type = SCENE_TYPE_NORMAL,
    .text = "Game Design and Programming by Saffron \nMusic and Story by Fantastic Fox \nArt by Roselion",
    .nextSceneA = 34,
    .nextSceneB = 34,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 1, .music = 1,
  },
  {
    .id = 34,
    .type = SCENE_TYPE_GOOD_ENDING,
    .text = "THE END",
    .nextSceneA = -1,
    .nextSceneB = -1,
    .triggerQuiz = -1,
    .questionId = -1,
    .bg = 1, .music = 1,
  },
};
const Scene * const SCENES = SCENES_DATA;
const u16 SCENES_COUNT = 35;

// ---- Quizzes ----
static const u16 _QUIZ_CATS_0[] = { 1, 0, 12, 14, 11 };
static const u16 _QUIZ_CATS_1[] = { 1, 0, 12, 14, 11 };
static const u16 _QUIZ_CATS_2[] = { 6 };
static const u16 _QUIZ_CATS_3[] = { 7 };
static const u16 _QUIZ_CATS_4[] = { 8 };
static const u16 _QUIZ_CATS_5[] = { 9 };
static const u16 _QUIZ_CATS_6[] = { 10 };
static const u16 _QUIZ_CATS_7[] = { 2 };
static const u16 _QUIZ_CATS_8[] = { 3 };
static const u16 _QUIZ_CATS_9[] = { 4 };
static const u16 _QUIZ_CATS_10[] = { 5 };
static const Quiz QUIZZES_DATA[] = {
  {
    .id = 0,
    .name = "General Knowledge",
    .wrongLimit = 2,
    .questionCount = 3,
    .categories = _QUIZ_CATS_0,
    .categoryCount = (u16)(sizeof(_QUIZ_CATS_0)/sizeof(_QUIZ_CATS_0[0])),
  },
  {
    .id = 1,
    .name = "General Knowledge",
    .wrongLimit = 2,
    .questionCount = 5,
    .categories = _QUIZ_CATS_1,
    .categoryCount = (u16)(sizeof(_QUIZ_CATS_1)/sizeof(_QUIZ_CATS_1[0])),
  },
  {
    .id = 2,
    .name = "Internal 1",
    .wrongLimit = 0,
    .questionCount = 1,
    .categories = _QUIZ_CATS_2,
    .categoryCount = (u16)(sizeof(_QUIZ_CATS_2)/sizeof(_QUIZ_CATS_2[0])),
  },
  {
    .id = 3,
    .name = "Internal 2",
    .wrongLimit = 0,
    .questionCount = 1,
    .categories = _QUIZ_CATS_3,
    .categoryCount = (u16)(sizeof(_QUIZ_CATS_3)/sizeof(_QUIZ_CATS_3[0])),
  },
  {
    .id = 4,
    .name = "Internal 3",
    .wrongLimit = 0,
    .questionCount = 1,
    .categories = _QUIZ_CATS_4,
    .categoryCount = (u16)(sizeof(_QUIZ_CATS_4)/sizeof(_QUIZ_CATS_4[0])),
  },
  {
    .id = 5,
    .name = "Internal 4",
    .wrongLimit = 0,
    .questionCount = 1,
    .categories = _QUIZ_CATS_5,
    .categoryCount = (u16)(sizeof(_QUIZ_CATS_5)/sizeof(_QUIZ_CATS_5[0])),
  },
  {
    .id = 6,
    .name = "Internal 5",
    .wrongLimit = 0,
    .questionCount = 1,
    .categories = _QUIZ_CATS_6,
    .categoryCount = (u16)(sizeof(_QUIZ_CATS_6)/sizeof(_QUIZ_CATS_6[0])),
  },
  {
    .id = 7,
    .name = "Demon Quiz 1",
    .wrongLimit = 0,
    .questionCount = 1,
    .categories = _QUIZ_CATS_7,
    .categoryCount = (u16)(sizeof(_QUIZ_CATS_7)/sizeof(_QUIZ_CATS_7[0])),
  },
  {
    .id = 8,
    .name = "Demon Quiz 2",
    .wrongLimit = 0,
    .questionCount = 1,
    .categories = _QUIZ_CATS_8,
    .categoryCount = (u16)(sizeof(_QUIZ_CATS_8)/sizeof(_QUIZ_CATS_8[0])),
  },
  {
    .id = 9,
    .name = "Demon Quiz 3",
    .wrongLimit = 0,
    .questionCount = 1,
    .categories = _QUIZ_CATS_9,
    .categoryCount = (u16)(sizeof(_QUIZ_CATS_9)/sizeof(_QUIZ_CATS_9[0])),
  },
  {
    .id = 10,
    .name = "Demon Quiz 4",
    .wrongLimit = 0,
    .questionCount = 1,
    .categories = _QUIZ_CATS_10,
    .categoryCount = (u16)(sizeof(_QUIZ_CATS_10)/sizeof(_QUIZ_CATS_10[0])),
  },
};
const Quiz * const QUIZZES = QUIZZES_DATA;
const u16 QUIZZES_COUNT = 11;

// ---- Category Question Indexes ----
static const u16 _CAT_QIDX_0[] = { 20, 21, 22, 23, 24, 25, 26, 27, 28, 29 };
static const u16 _CAT_QIDX_1[] = { 30, 31, 32, 33, 34, 35, 36, 37, 38, 39 };
static const u16 _CAT_QIDX_2[] = { 65 };
static const u16 _CAT_QIDX_3[] = { 66 };
static const u16 _CAT_QIDX_4[] = { 67 };
static const u16 _CAT_QIDX_5[] = { 68 };
static const u16 _CAT_QIDX_6[] = { 60 };
static const u16 _CAT_QIDX_7[] = { 61 };
static const u16 _CAT_QIDX_8[] = { 62 };
static const u16 _CAT_QIDX_9[] = { 63 };
static const u16 _CAT_QIDX_10[] = { 64 };
static const u16 _CAT_QIDX_11[] = { 10, 11, 12, 13, 14, 15, 16, 17, 18, 19 };
static const u16 _CAT_QIDX_12[] = { 40, 41, 42, 43, 44, 45, 46, 47, 48, 49 };
static const u16 _CAT_QIDX_13[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
static const u16 _CAT_QIDX_14[] = { 50, 51, 52, 53, 54, 55, 56, 57, 58, 59 };
const u16 * const CATEGORY_QUESTION_INDEXES[] = {
  _CAT_QIDX_0,
  _CAT_QIDX_1,
  _CAT_QIDX_2,
  _CAT_QIDX_3,
  _CAT_QIDX_4,
  _CAT_QIDX_5,
  _CAT_QIDX_6,
  _CAT_QIDX_7,
  _CAT_QIDX_8,
  _CAT_QIDX_9,
  _CAT_QIDX_10,
  _CAT_QIDX_11,
  _CAT_QIDX_12,
  _CAT_QIDX_13,
  _CAT_QIDX_14,
};
const u16 CATEGORY_QUESTION_COUNTS[] = {
  10,
  10,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  10,
  10,
  10,
  10,
};
